---
output: github_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#",
  fig.width = 10, fig.height = 5,
  fig.align = "center",
  fig.path  = "../Figures/",
  dev = 'svg'
)
```

```{r}
source("main_pkgs.R", encoding = "UTF-8")

infile <- "data/MOD13A2_Henan_2015_2020.rda"

if (!file.exists(infile)) {
  indir <- path.mnt("I:/Research/phenology/gee_whittaker/data-raw/NorthChina")
  file_vi <- glue("{indir}/MOD13A2_Henan_2016_2020_EVI.tif")
  file_qc <- glue("{indir}/MOD13A2_Henan_2016_2020_SummaryQA.tif")
  file_doy <- glue("{indir}/MOD13A2_Henan_2016_2020_DayOfYear.tif")

  # dates = terra::rast(infile) %>% names() %>%
  #     substr(1, 10) %>% as.Date("%Y_%m_%d")
  dates <- modis_date("2015-01-01", "2020-12-31", 16) # make sure dates are in line with that in tiff
  l <- read_rast(file_vi, dates) %>% rast2mat()
  l_qc <- read_rast(file_qc) %>% rast2mat()
  l_doy <- read_rast(file_doy) %>% rast2mat()
  
  I_grid <- l$I_grid
  d_coord <- l$d_coord[I_grid, ]
  data <- listk(
    VI = l$mat[I_grid, ] / 1e4,
    QC = l_qc$mat[I_grid, ],
    DOY = l_doy$mat[I_grid, ],
    dates = l$dates, qcFUN = qc_summary
  )
  save(data, d_coord, file = infile)
} else {
  load(infile)
  n <- nrow(data$QC)
}

## Parameter setting
# If provided, LCs should have the same length as `data$VI`
LCs <- NULL
nptperyear <- 23
opt_old <- phenofit::get_options()

# Different parameters for different land covers (LCs) refered by TIMESAT
# Name of `list_options` corresponds to `LCs` code
list_options <- list(
  "1" = list(),
  "2" = list(),
  default = list(
    wFUN = wTSM, wmin = 0.2,
    verbose = FALSE,
    season = list(
      # rFUN = "smooth_wWHIT", lambda = 0.5,
      rFUN = "smooth_wHANTS", nf = 6,
      maxExtendMonth = 12, r_min = 0.0
    ),
    # fine fitting parameters
    fitting = list(
      nextend = 1, minExtendMonth = 0, maxExtendMonth = 0.5,
      methods = c("AG", "Zhang", "Beck", "Elmore", "Gu")[3], # ,"klos",, 'Gu'
      iters = 1,
      minPercValid = 0
    )
  )
)
do.call(phenofit::set_options, list_options$default)
```

## 运行说明

### (a) 非并行版本

> 注意：**该版本是非并行的版本**

- `runningId`：`step`次循环打印一次进度，请根据你的样本大小设置合适的值。

- `n_run`：只运行前`n_run`个点。先确保程序在测试的站点上可以跑通，然后再运行所有（设置`n_run=n`）。

- `outfile`：如果指定outfile，则保存数据，否则返回`res`
```{r}
# the following function used many global variables, please make sure run the above
# script before

#' main_phenofit
#' 
#' @return 
#' - `t`: info of running time
#' - `res`: extracted phenological metrics
main_phenofit <- function(n_run = 10, step = 1000, outfile = NULL, .parallel = FALSE) {
  `%dof%` <- ifelse(.parallel, foreach::`%dopar%`, foreach::`%do%`)
  inds <- 1:n

  t <- system.time({
    res <- foreach(i = inds %>% set_names(., .), icount(n_run)) %dof% {
      runningId(i, step)

      if (!is.null(LCs)) {
        LC <- LCs[i]
        do.call(set_options, list_options[[LC]])
      }
      tryCatch({
        d <- get_input(i, data)
        r <- phenofit_point(d, plot = FALSE, period = c(2015, 2020))$pheno
      }, error = function(e) {
        message(sprintf('%s', e$message))
      })
    }
  })

  if (is.null(outfile)) {
    res
  } else save(res, t, file = outfile)
}

# outfile <- "OUTPUT/phenofit_V0.3.5_wHANTS_MODIS_Henan/pheno_Henan_MODIS_V6.1.rda"
res = main_phenofit(10, 1)
str(res[1:3], 2) # only show the first three
```

### (b) 并行版本

#### windows版本
- `ncluster`：并行核数，根据自己的电脑配置设定，让电脑以80%的能力去跑，以免影响办公软件。

> windows并行较为复杂，需要对每个cluster执行加载包、加载函数、加载数据命令，如下：

```{r phenofit_parallel}
library(parallel)
ncluster = 4
InitCluster(ncluster, kill = FALSE)
cl = getOption("cl")

.tmp = clusterEvalQ(cl, {
    library(Ipaper)
    library(phenofit)
    source("main_pkgs.R", encoding = "UTF-8")
})
clusterExport(cl, c("data", "LCs"))
```

```{r}
res = main_phenofit(10, 1, .parallel = TRUE)
str(res[1:3], 2) # only show the first three
```


#### linux版本

```{r, eval=FALSE}
ncluster <- 4
InitCluster(ncluster, kill = FALSE)

res <- main_phenofit(10, 1, ..parallel = TRUE)
str(res[1:3], 2) # only show the first three
```

> 请自行比较哪个版本的并行更简单！
